In [ ]:
import numpy as np
import pandas as pd


In [ ]:
path='/makeSenseOfCensus.csv'
data= pd.read_csv('/makeSenseOfCensus.csv')

In [ ]:
data.head()

age  education-num  race  sex  capital-gain  capital-loss  hours-per-week  \
0   39             13     4    1          2174             0              40   
1   50             13     4    1             0             0              13   
2   38              9     4    1             0             0              40   
3   53              7     2    1             0             0              40   
4   28             13     2    0             0             0              40   

   income  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
data=np.genfromtxt(path,delimiter=",",skip_header=1)
print("\n data: \n\n",type(data))


 data: 

 <class 'numpy.ndarray'>


In [ ]:
data

In [ ]:
type(data)

In [ ]:
new_record=np.array([[50,9,4,1,0,0,40,0]])
da = np.concatenate((data,new_record),axis=0)
print(da)
age=da[:,0]
print (age)
print (age.max())
max_age=(age.max())
min_age=(age.min())
mean_age=(age.mean())
std=(np.std(age))

[[39 13  4 ...  0 40  0]
 [50 13  4 ...  0 13  0]
 [38  9  4 ...  0 40  0]
 ...
 [40 10  4 ...  0 40  0]
 [39 13  4 ...  0 50  1]
 [50  9  4 ...  0 40  0]]
[39 50 38 ... 40 39 50]
90


In [97]:
print("Race")
race=da[:,2]
print(race)
print(race.size)

r=(race==0)
race_0=race[r]

r1=(race==1)
race_1=race[r1]

r2=(race==2)
race_2=race[r2]

r3=(race==3)
race_3=race[r3]

r4=(race==4)
race_4=race[r4]

len_r0=(race_0.size)
print("In race 0 there are:",len_r0)

len_r1=(race_1.size)
print('In race 1 there are :',len_r1)

len_r2=(race_2.size)
print('In race 2 there are :',len_r2)

len_r3=(race_3.size)
print('In race 3 there are :',len_r3)

len_r4=(race_4.size)
print("in race 4 there are",race_4.size)

minority_race= print('The minority race is race 3:',len_r3)





Race
[4 4 4 ... 4 4 4]
1001
In race 0 there are: 10
In race 1 there are : 27
In race 2 there are : 110
In race 3 there are : 6
in race 4 there are 848
The minority race is race 3: 6


In [93]:
Education=da[:,1]

e1=(Education>10)
edu_grtthan10=Education[e1]
print(edu_grtthan10)


e2=(Education<=10)
edu_lessthan10=Education[e2]
print(edu_lessthan10)


[13 13 13 14 14 13 13 13 12 11 14 16 13 12 13 12 13 13 13 14 11 11 15 13
 11 13 16 13 13 12 13 14 16 11 13 16 12 14 13 14 13 15 11 13 13 13 13 12
 12 13 12 14 11 11 13 13 13 14 14 12 14 11 13 13 13 13 13 14 16 13 13 14
 14 14 13 13 13 12 13 13 11 15 13 14 13 12 12 15 13 11 13 13 14 14 13 12
 13 14 15 13 13 13 13 13 14 13 12 12 12 13 14 13 14 11 13 11 14 12 11 13
 11 12 13 13 13 13 11 14 13 13 12 13 11 14 13 12 13 13 13 13 11 14 16 13
 14 14 13 12 14 13 12 11 12 13 13 14 13 11 13 12 13 13 13 12 13 13 13 11
 11 11 13 13 13 14 12 15 11 13 16 11 13 13 13 14 14 11 16 13 12 13 13 13
 13 13 15 13 13 12 14 14 13 13 13 15 13 11 13 13 13 13 16 16 13 16 14 14
 12 13 11 13 14 13 12 14 14 13 13 13 16 13 13 13 11 13 13 13 13 13 11 11
 13 13 14 11 13 13 13 13 11 13 16 13 13 11 11 14 13 11 11 13 11 13 14 13
 12 14 13 13 11 11 14 11 13 13 13 13 13 13 14 11 13 16 13 13 13 13 14 13
 13 11 13 13 13 11 13 11 13 15 14 13 13 12 13 13 14 14 14 15 13 12 13 14
 13 12 13 13 11 13 13 14 12 11 13 11 14 13 13]
[ 9 

In [ ]:
Income=da[:,7]
print(Income)
I1=(Income==Income.min())
Income1=Income[I1]
print("mean of low income:",Income1.mean())
I2=(Income==Income.max())
Income2=Income[I2]
print("mean of high income:",Income2.mean())


[0 0 0 ... 0 1 0]
mean of low income: 0.0
mean of high income: 1.0


In [ ]:
pd.DataFrame(da)

0   1  2  3      4  5   6  7
0     39  13  4  1   2174  0  40  0
1     50  13  4  1      0  0  13  0
2     38   9  4  1      0  0  40  0
3     53   7  2  1      0  0  40  0
4     28  13  2  0      0  0  40  0
...   ..  .. .. ..    ... ..  .. ..
996   45  14  4  1      0  0  45  0
997   48  13  4  1      0  0  58  1
998   40  10  4  1   2580  0  40  0
999   39  13  4  1  15024  0  50  1
1000  50   9  4  1      0  0  40  0

[1001 rows x 8 columns]

In [ ]:
a=np.array([[1,2],[2,1]])
b=np.array([[5,6],[6,0]])
np.concatenate((a,b),axis=1)

array([[1, 2, 5, 6],
       [2, 1, 6, 0]])